version: '3.8'

services:
  db:
    container_name: mtg_db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./TelegramBot/MySql/dbdata:/var/lib/mysql
      - ./TelegramBot/MySql/init/:/docker-entrypoint-initdb.d
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"

  main:
    container_name: mtg_telegram_alerter
    restart: always
    # platform: linux/arm64/v8
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env